### ISSUE TITLE
Error that "VCRUNTIME140D.dll" and  "ucrtbased.dll" are missing, although vcredist2019 is installed

### ISSUE THREAD

**Issue by LPanic** [mrKallah/Red-Alert-2-arrow-to-wasd#1]
When I try to launch it says that "VCRUNTIME140D.dll" and  "ucrtbased.dll" are missing. I made sure that vcredist 2019 (both x86 and x64) are installed , but still the same error. Running on Win10 with default install directory and CNCnet launcher (I amended the launch parameter as described). Any help would be greatly appreciated.

And a BIG thx for your work! This is exactly what I was looking for :)

**Comment by mrKallah** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=52685

Try installing this. I haven't really looked at this since 4 years ago, as I stopped playing but I can try to give support. Give me a heads up whether that worked or not. 

I think it might be that a default lib that came with windows back then is missing, but not sure.

**Comment by LPanic** [comment]
This did the trick! You Sir, are awesome! :D
Thank you very much. Hopefully this gives me the edge so I can win against my friends :P
